-- duplicated schema with new fields for testing
CREATE TABLE Students_copy (
        intern_id INTEGER PRIMARY KEY AUTOINCREMENT,
        full_name TEXT,
        pronouns TEXT,
        status TEXT,
        email TEXT,
        mobile TEXT,
        course TEXT,
        course_major TEXT,
        link_to_application_doc TEXT,
        read_student_handbook TEXT,
        read_student_projects TEXT,
        cover_letter_projects TEXT,
        cover_letter_concept TEXT,
        cover_letter_technical TEXT,
        pronunciation TEXT,
        project TEXT,
        project_id INTEGER, -- new project field for project table association
        start_date DATE,
        end_date DATE,
        hours_per_week INTEGER,
        intake TEXT,
        supervisor_email TEXT,
        wehi_email TEXT,
        summary_tech_skills TEXT,
        summary_experience TEXT,
        summary_interest_in_projects TEXT,
        pre_internship_summary_recommendation_external TEXT,
        pre_internship_summary_recommendation_internal TEXT,
        pre_internship_summary_recommendation_internal_id INTEGER,  -- new field for internal skills association
        pre_internship_technical_rating TEXT,
        pre_internship_social_rating TEXT,
        pre_internship_learning_quickly TEXT,
        pre_internship_enthusiasm TEXT,
        pre_internship_experience TEXT,
        pre_internship_communication TEXT,
        pre_internship_adaptable TEXT,
        pre_internship_problem_solver TEXT,
        post_internship_comments TEXT,
        post_internship_adaptability TEXT,
        post_internship_learn_technical TEXT,
        post_internship_learn_conceptual TEXT,
        post_internship_collaborative TEXT,
        post_internship_ambiguity TEXT,
        post_internship_complexity TEXT,
        post_internship_summary_rating_internal TEXT,
        post_internship_summary_rating_external TEXT,
        github_username, extra_notes text,
        remote_internship TEXT,
        code_of_conduct TEXT,
        facilitator_follower TEXT,
        listener_or_talker TEXT,
        thinker_brainstormer TEXT,
        why_applied TEXT,
        projects_recommended TEXT,
        -- NEW: Foreign key constraints
        FOREIGN KEY (project_id) REFERENCES Projects(id),
        FOREIGN KEY (pre_internship_summary_recommendation_internal_id) REFERENCES Internal_eval_levels(id)
        );

-- insert existing data from original to new database
INSERT INTO Students_copy (
        intern_id,
        full_name,
        pronouns,
        status,
        email,
        mobile,
        course,
        course_major,
        link_to_application_doc,
        read_student_handbook,
        read_student_projects,
        cover_letter_projects,
        cover_letter_concept,
        cover_letter_technical,
        pronunciation,
        project,
        start_date,
        end_date,
        hours_per_week,
        intake,
        supervisor_email,
        wehi_email,
        summary_tech_skills,
        summary_experience,
        summary_interest_in_projects,
        pre_internship_summary_recommendation_external,
        pre_internship_summary_recommendation_internal,
        pre_internship_technical_rating,
        pre_internship_social_rating,
        pre_internship_learning_quickly,
        pre_internship_enthusiasm,
        pre_internship_experience,
        pre_internship_communication,
        pre_internship_adaptable,
        pre_internship_problem_solver,
        post_internship_comments,
        post_internship_adaptability,
        post_internship_learn_technical,
        post_internship_learn_conceptual,
        post_internship_collaborative,
        post_internship_ambiguity,
        post_internship_complexity,
        post_internship_summary_rating_internal,
        post_internship_summary_rating_external,
        github_username, extra_notes,
        remote_internship,
        code_of_conduct,
        facilitator_follower,
        listener_or_talker,
        thinker_brainstormer,
        why_applied,
        projects_recommended)
SELECT intern_id,
        full_name,
        pronouns,
        status,
        email,
        mobile,
        course,
        course_major,
        link_to_application_doc,
        read_student_handbook,
        read_student_projects,
        cover_letter_projects,
        cover_letter_concept,
        cover_letter_technical,
        pronunciation,
        project,
        start_date,
        end_date,
        hours_per_week,
        intake,
        supervisor_email,
        wehi_email,
        summary_tech_skills,
        summary_experience,
        summary_interest_in_projects,
        pre_internship_summary_recommendation_external,
        pre_internship_summary_recommendation_internal,
        pre_internship_technical_rating,
        pre_internship_social_rating,
        pre_internship_learning_quickly,
        pre_internship_enthusiasm,
        pre_internship_experience,
        pre_internship_communication,
        pre_internship_adaptable,
        pre_internship_problem_solver,
        post_internship_comments,
        post_internship_adaptability,
        post_internship_learn_technical,
        post_internship_learn_conceptual,
        post_internship_collaborative,
        post_internship_ambiguity,
        post_internship_complexity,
        post_internship_summary_rating_internal,
        post_internship_summary_rating_external,
        github_username, extra_notes,
        remote_internship,
        code_of_conduct,
        facilitator_follower,
        listener_or_talker,
        thinker_brainstormer,
        why_applied,
        projects_recommended
FROM Students;

-- add corresponding value to new fields
UPDATE students_copy
SET project_id = 
        (SELECT projects.id FROM projects
        WHERE projects.name = students_copy.project);

UPDATE students_copy
SET pre_internship_summary_recommendation_internal_id =
        (SELECT Internal_eval_levels.id FROM Internal_eval_levels
        WHERE SUBSTR(
                students_copy.pre_internship_summary_recommendation_internal, 
                INSTR(students_copy.pre_internship_summary_recommendation_internal, '-') + 2
                ) 
        = Internal_eval_levels.name);
